### ISSUE TITLE
[Bug]: List Family Size error. crashes on Revit 2024

### ISSUE THREAD

**Issue by TugboatBen** [pyrevitlabs/pyRevit#2283]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Tools starts as it should, but stops part way through the scan with this error.
ERROR [pyrevit.revit] Error in ErrorSwallower Context. | <type 'exceptions.Exception'>:Saving failed.

### ⌨ Error/Debug Message

```shell
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\xxxxxxx\AppData\Roaming\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Analysis.panel\Tools.stack\Inspect.pulldown\ListFamilySizeCreator.pushbutton\ListFamilySizeCreator_script.py", line 113, in <module>
Exception: Saving failed.


Script Executor Traceback:
Autodesk.Revit.Exceptions.InvalidOperationException: Saving failed.
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.14.24016+1909" | Path: "C:\Users\bhunter\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "24.2" | Engine: IPY277 (277) | Path: "C:\Users\bhunter\AppData\Roaming\pyRevit-Master"
master | Product: "23.1.3" | Engine: IPY277 (277) | Path: "C:\Users\bhunter\AppData\Roaming\pyRevit-Master"
master | Product: "2022.1.5" | Engine: IPY277 (277) | Path: "C:\Users\bhunter\AppData\Roaming\pyRevit-Master"
master | Product: "2021.1.9" | Engine: IPY277 (277) | Path: "C:\Users\bhunter\AppData\Roaming\pyRevit-Master"
master | Product: "2020.2.9" | Engine: IPY277 (277) | Path: "C:\Users\bhunter\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
DC_Tools | Type: Unknown | Repo: "" | Installed: "C:\Users\bhunter\AppData\Roaming\Autodesk\Revit\Addins\LCI Addins\Extensions\DC_Tools.extension"
==> Default Extension Search Path
C:\Users\bhunter\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
C:\Users\bhunter\AppData\Roaming\Autodesk\Revit\Addins\LCI Addins\Extensions
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
23.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
2022.1.5 | Version: 22.1.50.17 | Build: 20230915_1530(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.9 | Version: 21.1.90.15 | Build: 20230907_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
PID: 32924 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
PID: 37248 | 24.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 0 | Path: "C:\Program Files\Autodesk\Revit 2024"
==> User Environment
Microsoft Windows 10 [Version 10.0.19045]
Executing User: LCI\bhunter
Active User: LCI\bhunter
Admin Access: No
%APPDATA%: "C:\Users\bhunter\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
No .Ne-Core Target Packs are installed.
pyRevit CLI v4.8.14.24016+1909.ee814ee2f686d23db8bb6ff80d8bb918ff9adc99
```

**Comment by sanzoghenzo** [comment]
Hi @TugboatBen, sorry for the delay...
Can you please try to run the command with debug enabled (hold ctrl while clicking on the button)?
It might give you more information about the family that can't be saved (the script saves the families that don't have a path to a temporary folder in order to calculate its size).

Does this happen regardless of the model that you run the command in?

**Comment by angelmarquez2001** [comment]
i have exactly the same problem


[Window Title]
PyRevitLoader - Error Loading pyRevit

[Main Instruction]
IronPython Traceback:
Traceback (most recent call last):
  File "C:\Program Files\pyRevit-Master\bin\engines\pyRevitLoader.py", line 30, in <module>
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py", line 24, in <module>
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\loader\sessioninfo.py", line 14, in <module>
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\runtime\__init__.py", line 505, in <module>
Exception: Error dynamically compiling pyRevit runtime

Script Executor Traceback:
IronPython.Runtime.Exceptions.PythonException: Error dynamically compiling pyRevit runtime
   at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   at IronPython.Runtime.PythonContext.InitializeModule(String fileName, ModuleContext moduleContext, ScriptCode scriptCode, ModuleOptions options)
   at IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String name, String path)
   at IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
   at IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
   at IronPython.Runtime.Importer.ImportFromPath(CodeContext context, String name, String fullName, List path)
   at IronPython.Runtime.Importer.ImportNestedModule(CodeContext context, PythonModule module, String[] parts, Int32 current, List path)
   at IronPython.Runtime.Importer.ImportFrom(CodeContext context, Object from, String name)
   at IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
   at IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   at IronPython.Runtime.PythonContext.InitializeModule(String fileName, ModuleContext moduleContext, ScriptCode scriptCode, ModuleOptions options)
   at IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String name, String path)
   at IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
   at IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
   at IronPython.Runtime.Importer.ImportFromPath(CodeContext context, String name, String fullName, List path)
   at IronPython.Runtime.Importer.ImportNestedModule(CodeContext context, PythonModule module, String[] parts, Int32 current, List path)
   at IronPython.Runtime.Importer.ImportFrom(CodeContext context, Object from, String name)
   at IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
   at IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   at IronPython.Runtime.PythonContext.InitializeModule(String fileName, ModuleContext moduleContext, ScriptCode scriptCode, ModuleOptions options)
   at IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String

**Comment by sanzoghenzo** [comment]
> i have exactly the same problem

You don't. 
Follow the installation troubleshooting guide linked in the first post to fix that.
