### ISSUE TITLE
[Bug]:  'Match' does not work for me in the latest WIP (pyRevit_CLI_5.0.0.24325_admin_signed) version in 2025 Revit

### ISSUE THREAD

**Issue by Garyebeck** [pyrevitlabs/pyRevit#2464]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

The 'Match' does not work for me in the latest WIP (pyRevit_CLI_5.0.0.24325_admin_signed) version in 2025 Revit
I'm running 2025 Revit on Windows 10. Before installing I uninstalled all verisons of pyRevit and previously went though my Regedit to remove references to pyRevit.

The feature open and the drop downs work, but the basic Match properties does not do anything. I've opened the drop downs and toggle the selections but there is no change.  I get no error messages, it just does not copy and paste the Graphic Overrides (Projection Lines, Surface Patterns, Surface Transparency, Cut Lines, Cut Patterns).

### ⌨ Error/Debug Message

```shell
'Match' does not work for me in the latest WIP (pyRevit_CLI_5.0.0.24325_admin_signed) version in 2025 Revit
```

### ⏲️ Expected behavior

Clicking 'Match' should allow selection of any item to copy all Graphic Overrides (Projection Lines, Surface Patterns, Surface Transparency, Cut Lines, Cut Patterns), then selecting a second item should paste those graphic overrides to that view of the selected item

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Windows 10 PC
2025 Revit latest version.
```

**Comment by sanzoghenzo** [comment]
Did you see the instructions under the "Error/Debug" message when you filed the issue? It asks you to CTRL+click on the command button and report the debug messages here, that way we can better analyze the problem.

Also, the "to reproduce" section is helpful to us to understend exactly the actions you performed step by step (I know that it feels like replicating the description, and in this case is trivial, but it could help spot the conditions where tha unexpected behavior raises).

Finally: does this happen with any file, or did you try only with one model?

**Comment by Garyebeck** [comment]
Andrea,

To answer your questions:


Did you see the instructions under the "Error/Debug" message when you filed the issue?  No, I didn’t see this

It asks you to CTRL+click on the command button and report the debug messages here, that way we can better analyze the problem. I will try to find this location to report debug messages.

Also, the "to reproduce" section is helpful to us to understand exactly the actions you performed step by step (I know that it feels like replicating the description, and in this case is trivial, but it could help spot the conditions where tha unexpected behavior raises).
I’m running Windows 10, 2025 Revit and the WIP 5.** version of pyRevit. I simply click on the ‘Match’ button and then do the select item to collect the graphic overrides, and then paste on another item to set those same graphic overrides.
Nothing happens.   Previously the 2024 version of pyRevit did this with no issues when running 2024 Revit.

Finally: does this happen with any file, or did you try only with one model?
This happens with all 2025 Revit .rvt files.

PS; I am slow to learn the GitHub interface for communicating properly in the pyRevitlabs/pyRevit WIP 5.** forum(?)
Each time I login things appear to be arrange differently.  Is there a link that you can share?
Is there any tutorial to explains how to properly navigate and post issues?

This a new issue I’d like to post for consideration.  I will try to find the link to add this as a new issue.

Windows 10, running 2025 Revit and the WIP 5.** version of pyRevit.
Under the ‘Match’ menu, I just tried "Match Paint" selecting a Catch Basin family .rfa and attempting to paste to an identical Catch Basin .rfa family.
I wanted the copy and paste the magenta line color graphic override, to a catch basin with no graphic overrides.  It provided this error

“
ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:The element's face cannot be painted.
Parameter name: face

IronPython Traceback:
Traceback (most recent call last):
File "C:\Program Files\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\edit1.stack\Match.splitpushbutton\Match Paint.pushbutton\script.py", line 36, in <module>
Exception: The element's face cannot be painted.
Parameter name: face

Script Executor Traceback:
Autodesk.Revit.Exceptions.ArgumentException: The element's face cannot be painted.
Parameter name: face
at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame) in /_/Src/Microsoft.Dynamic/Interpreter/Instructions/ControlFlowInstructions.cs:line 405
at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception) in /_/Src/Microsoft.Dynamic/Interpreter/Interpreter.cs:line 135
at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception) in /_/Src/Microsoft.Dynamic/Interpreter/Interpreter.cs:line 150
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) in /_/Src/Microsoft.Dynamic/Interpreter/Interpreter.cs:line 96
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1) in /_/Src/Microsoft.Dynamic/Interpreter/LightLambda.Generated.cs:line 86
at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx) in D:\a\pyRevit\pyRevit\dev\modules\pyRevitLabs.IronPython2\Src\IronPython\Compiler\PythonScriptCode.cs:line 65
at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope) in D:\a\pyRevit\pyRevit\dev\modules\pyRevitLabs.IronPython2\Src\IronPython\Compiler\RuntimeScriptCode.cs:line 85
at Microsoft.Scripting.Hosting.CompiledCode.Execute(ScriptScope scope) in /_/Src/Microsoft.Scripting/Hosting/CompiledCode.cs:line 63
at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
“

**Comment by Garyebeck** [comment]
I did some light programming years ago and I have almost 20 yrs on Revit.

If I wanted to start to learn python and or ironpython. Does it matter which one I find tutorials for? Are they essentially the same?

From Gary Beck’s iPhone
Eco-Holdings 3D Design & Engineering

On Nov 23, 2024, at 12:46 PM, Gary Beck ***@***.***> wrote:

﻿
Andrea,

To answer your questions:


Did you see the instructions under the "Error/Debug" message when you filed the issue?  No, I didn’t see this

It asks you to CTRL+click on the command button and report the debug messages here, that way we can better analyze the problem. I will try to find this location to report debug messages.

Also, the "to reproduce" section is helpful to us to understand exactly the actions you performed step by step (I know that it feels like replicating the description, and in this case is trivial, but it could help spot the conditions where tha unexpected behavior raises).
I’m running Windows 10, 2025 Revit and the WIP 5.** version of pyRevit. I simply click on the ‘Match’ button and then do the select item to collect the graphic overrides, and then paste on another item to set those same graphic overrides.
Nothing happens.   Previously the 2024 version of pyRevit did this with no issues when running 2024 Revit.

Finally: does this happen with any file, or did you try only with one model?
This happens with all 2025 Revit .rvt files.

PS; I am slow to learn the GitHub interface for communicating properly in the pyRevitlabs/pyRevit WIP 5.** forum(?)
Each time I login things appear to be arrange differently.  Is there a link that you can share?
Is there any tutorial to explains how to properly navigate and post issues?

This a new issue I’d like to post for consideration.  I will try to find the link to add this as a new issue.

Windows 10, running 2025 Revit and the WIP 5.** version of pyRevit.
Under the ‘Match’ menu, I just tried "Match Paint" selecting a Catch Basin family .rfa and attempting to paste to an identical Catch Basin .rfa family.
I wanted the copy and paste the magenta line color graphic override, to a catch basin with no graphic overrides.  It provided this error

“
ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:The element's face cannot be painted.
Parameter name: face

IronPython Traceback:
Traceback (most recent call last):
File "C:\Program Files\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\edit1.stack\Match.splitpushbutton\Match Paint.pushbutton\script.py", line 36, in <module>
Exception: The element's face cannot be painted.
Parameter name: face

Script Executor Traceback:
Autodesk.Revit.Exceptions.ArgumentException: The element's face cannot be painted.
Parameter name: face
at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame) in /_/Src/Microsoft.Dynamic/Interpreter/Instructions/ControlFlowInstructions.cs:line 405
at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception) in /_/Src/Microsoft.Dynamic/Interpreter/Interpreter.cs:line 135
at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception) in /_/Src/Microsoft.Dynamic/Interpreter/Interpreter.cs:line 150
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) in /_/Src/Microsoft.Dynamic/Interpreter/Interpreter.cs:line 96
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1) in /_/Src/Microsoft.Dynamic/Interpreter/LightLambda.Generated.cs:line 86
at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx) in D:\a\pyRevit\pyRevit\dev\modules\pyRevitLabs.IronPython2\Src\IronPython\Compiler\PythonScriptCode.cs:line 65
at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope) in D:\a\pyRevit\pyRevit\dev\modules\pyRevitLabs.IronPython2\Src\IronPython\Compiler\RuntimeScriptCode.cs:line 85
at Microsoft.Scripting.Hosting.CompiledCode.Execute(ScriptScope scope) in /_/Src/Microsoft.Scripting/Hosting/CompiledCode.cs:line 63
at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
“

**Comment by sanzoghenzo** [comment]
> I did some light programming years ago and I have almost 20 yrs on Revit. If I wanted to start to learn python and or ironpython. Does it matter which one I find tutorials for? Are they essentially the same?

Please [use the forum](https://discourse.pyrevitlabs.io) to ask for this kind of help.
While not directly asking to your question, [here's a quickstart guide](https://discourse.pyrevitlabs.io/t/quickstart-in-the-realm-of-pyrevit-and-the-revit-api/2050) for pyRevit.
IronPython is stuck at version 2.7, while the official python is now at version 3.13, with changes to both the sintax and the base library, so you might find guides for python that mentions functions or modules not present in IronPython.
