### ISSUE TITLE
[Bug]: WIP 5.*** pyRevit "Match Paint" return this error

### ISSUE THREAD

**Issue by Garyebeck** [pyrevitlabs/pyRevit#2465]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

Running Windows 10, running 2025 Revit and the WIP 5.** version of pyRevit.

Under the ‘Match’ menu, I just tried "Match Paint" selecting a Catch Basin family .rfa and attempting to paste to an identical Catch Basin .rfa family. 
I wanted the copy and paste the magenta line color graphic override, to a catch basin with no graphic overrides.  It provided the error below

### ⌨ Error/Debug Message

```shell
ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:The element's face cannot be painted. 
Parameter name: face

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Program Files\pyRevit-Master\extensions\pyRevitTools.extension\pyRevit.tab\Modify.panel\edit1.stack\Match.splitpushbutton\Match Paint.pushbutton\script.py", line 36, in <module>
Exception: The element's face cannot be painted.
Parameter name: face

Script Executor Traceback:
Autodesk.Revit.Exceptions.ArgumentException: The element's face cannot be painted.
Parameter name: face
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame) in /_/Src/Microsoft.Dynamic/Interpreter/Instructions/ControlFlowInstructions.cs:line 405
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception) in /_/Src/Microsoft.Dynamic/Interpreter/Interpreter.cs:line 135
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception) in /_/Src/Microsoft.Dynamic/Interpreter/Interpreter.cs:line 150
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame) in /_/Src/Microsoft.Dynamic/Interpreter/Interpreter.cs:line 96
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1) in /_/Src/Microsoft.Dynamic/Interpreter/LightLambda.Generated.cs:line 86
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx) in D:\a\pyRevit\pyRevit\dev\modules\pyRevitLabs.IronPython2\Src\IronPython\Compiler\PythonScriptCode.cs:line 65
 at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope) in D:\a\pyRevit\pyRevit\dev\modules\pyRevitLabs.IronPython2\Src\IronPython\Compiler\RuntimeScriptCode.cs:line 85
 at Microsoft.Scripting.Hosting.CompiledCode.Execute(ScriptScope scope) in /_/Src/Microsoft.Scripting/Hosting/CompiledCode.cs:line 63
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

### ⏲️ Expected behavior

Copy and Paste Graphic Overrides

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Windows 10
```

**Comment by sanzoghenzo** [comment]
The error clearly states that the element face cannot be painted.
Does this error occurs with any elements or does it happen only on this specific family?

Are you able to share the family/model that present the issue?


You could try to add these two lines before line 36 of the match paint script (ALT+Click on the button to open the directory in explorer)

```python
if revit.doc.IsPainted(dest_element.Id, dest_face):
    revit.doc.RemovePaint(dest_element.Id, dest_face)
```

but I don't believe this will solve anything, since you don't have graphic overrides...

**Comment by Garyebeck** [comment]
I will try to capture the output from this feature in the latest PyRevit in 2024 Revit and the latest WIP in 2025 Revit.

Then maybe a PyRevit programmer can identify what is different or wrong.



reload
Gary Beck, P. E.
3-D Design & Engineering
Eco-Holdings LLC (F-7395)
4010 Bluebonnet Blvd., Suite 114
Houston, TX 77025
Office: 713-377-4209
Cell: 713-540-1950
Texasengineer.com

On Dec 27, 2024, at 4:13 AM, Andrea Ghensi ***@***.***> wrote:

﻿

The error clearly states that the element face cannot be painted.
Does this error occurs with any elements or does it happen only on this specific family?

Are you able to share the family/model that present the issue?

You could try to add these two lines before line 36 of the match paint script (ALT+Click on the button to open the directory in explorer)

if revit.doc.IsPainted(dest_element.Id, dest_face):
    revit.doc.RemovePaint(dest_element.Id, dest_face)

but I don't believe this will solve anything, since you don't have graphic overrides...

**Comment by sanzoghenzo** [comment]
I don't quite understand your answer... 

anyway, are you working inside the families or not?
could this be the problem?

https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Paint-tool-does-not-work-on-certain-family-entities.html

**Comment by Garyebeck** [comment]
Sorry that I am unable to help on this so far.

The match graphic overrides feature has always just work perfectly in 2024 Revit and it was not family specific.  It just copied line types and pattern types from any object to any object. Then the WIP version did not work at all on 2025 Revit.

Gary Beck, P. E.
3-D Design & Engineering
Eco-Holdings LLC (F-7395)
4010 Bluebonnet Blvd., Suite 114
Houston, TX 77025
Office: 713-377-4209
Cell: 713-540-1950
Texasengineer.com

On Dec 27, 2024, at 12:19 PM, Andrea Ghensi ***@***.***> wrote:

﻿

I don't quite understand your answer...

anyway, are you working inside the families or not?
could this be the problem?

https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Paint-tool-does-not-work-on-certain-family-entities.html

**Comment by Garyebeck** [comment]
I am Revit user but unfortunately not a Python programmer or Pyrevit contributor with the except of what I’ve published on the copy/past of Graphic Overrides.

I am not working inside the Revit .rfa families. All of my Pyrevit use has been in .rvt project files.

Past this I can only ask simple questions.  Can I start with the installation?

From the download folder I can extract the files, but then I am unsure how to install or run the extracted files.
Is there a single file I should run?  The ‘Windows Installer Package’?
Does it just access the other files and run them in the correct sequence?
Or do I need to run the 4 ‘Application’ files individually?

Adding a ‘readme.txt’ file might with simple installation instructions be all that is needed.

Thanks,

Gary


***@***.***     ***@***.***

**Comment by Garyebeck** [comment]
Running only the ‘Windows Installer Package’ does not install Pyrevit into 2025 Revit. (After PC restart)

I’ll now try the 90,508 KB Application.

***@***.***

Success on the install!

Now I’ll test the copy/paste graphics override on the red border roof with green pattern.


***@***.***     ***@***.***

***@***.***

SUCCESS! It did not work at first. Then I  toggled the Check None and Check All, and then unchecked the ‘text position’ and It worked!
I had tried this before and it did not work.  You must click ‘Finish’ - <Enter> or right click does not work.


Thanks!

From: Gary Beck
Sent: Friday, January 3, 2025 4:45 PM
To: pyrevitlabs/pyRevit ***@***.***>; pyrevitlabs/pyRevit ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [pyrevitlabs/pyRevit] [Bug]: WIP 5.*** pyRevit "Match Paint" return this error (Issue #2465)

I am Revit user but unfortunately not a Python programmer or Pyrevit contributor with the except of what I’ve published on the copy/past of Graphic Overrides.

I am not working inside the Revit .rfa families. All of my Pyrevit use has been in .rvt project files.

Past this I can only ask simple questions.  Can I start with the installation?

From the download folder I can extract the files, but then I am unsure how to install or run the extracted files.
Is there a single file I should run?  The ‘Windows Installer Package’?
Does it just access the other files and run them in the correct sequence?
Or do I need to run the 4 ‘Application’ files individually?

Adding a ‘readme.txt’ file might with simple installation instructions be all that is needed.

Thanks,

Gary


***@***.***    ***@***.***

**Comment by sanzoghenzo** [comment]
This space is for reporting bugs and request new feature, not a support forum.
For that head to https://discourse.pyrevitlabs.io/

Also please note the following:

- don't use email to answer here, or at least remove the old messages from the mail body as it becomes unbeatable on github. 
- the WIP installers are war they are, a WIP thing. It was not intended for public consumption, but development have stalled and this is what users need to do if they want the latest unstable version.
- the wip installer are exactly like the stable installer that you find on the release page, it just downloads them all.
- we don't need the real time updates, just tell us what's wrong and what works 😉 

Having said that, I'm glad you solved your problems, but I don't get why you did all of this. The latest WIP version changed nothing of the match paint tool, and you already had a WIP version installed. So I must assume there was no problem to begin with.
Or are you saying this is not working as expected because you need to fiddle with the checkboxes to make it work?

@jmcouffin I know nothing about the match paint command, can you reproduce this?

**Comment by jmcouffin** [comment]
Nope.
I will just close this.
Thks @sanzoghenzo
